apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: airbnb
  labels:
    app: gateway
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: gateway
  type:
    LoadBalancer