kind: Deployment
apiVersion: apps/v1

metadata:
  name: postgres-db-deployment
  labels:
    app: postgresql-db
  namespace: airbnb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db

  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
      - name: postgres-db
        image: postgres
        ports:
        - containerPort: 5432

        volumeMounts:
        - name: volume
          mountPath: /data
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: wjdgid0103
        - name: POSTGRES_DB
          value: airbnb
        - name: PGDATA
          value: /data/pgdata
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: postgresql-data