server:
  port: 8080
---

spring:
  profiles: default

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://64.10.24.3:5432/airbnb
    username: postgres
    password: wjdgid0103

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: room
          destination: airbnb
          contentType: application/json
        event-out:
          destination: airbnb
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8082
---

spring:
  profiles: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://64.10.24.3:5432/airbnb
    username: postgres
    password: wjdgid0103
  cloud:
    stream:
      kafka:
        binder:
          brokers: 64.10.24.4:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: room
          destination: airbnb
          contentType: application/json
        event-out:
          destination: airbnb
          contentType: application/json
